config/routes.rb
Rails.application.routes.draw do

  resources :courses

  resources :departments

  resources :institutes

  devise_for :users

  resources :users, only: [:index, :show]

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'news' => 'static_pages#news'

end

app/models/institute.rb
class Institute < ActiveRecord::Base
	has_many :departments
end

app/controllers/institutes_controller.rb
class InstitutesController < ApplicationController
  before_action :set_institute, only: [:show, :edit, :update, :destroy]

  # GET /institutes
  # GET /institutes.json
  def index
    @institutes = Institute.all
  end

  # GET /institutes/1
  # GET /institutes/1.json
  def show
  end

  # GET /institutes/new
  def new
    @institute = Institute.new
  end

  # GET /institutes/1/edit
  def edit
  end

  # POST /institutes
  # POST /institutes.json
  def create
    @institute = Institute.new(institute_params)

    respond_to do |format|
      if @institute.save
        format.html { redirect_to @institute, notice: 'Institute was successfully created.' }
        format.json { render :show, status: :created, location: @institute }
      else
        format.html { render :new }
        format.json { render json: @institute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutes/1
  # PATCH/PUT /institutes/1.json
  def update
    respond_to do |format|
      if @institute.update(institute_params)
        format.html { redirect_to @institute, notice: 'Institute was successfully updated.' }
        format.json { render :show, status: :ok, location: @institute }
      else
        format.html { render :edit }
        format.json { render json: @institute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutes/1
  # DELETE /institutes/1.json
  def destroy
    @institute.destroy
    respond_to do |format|
      format.html { redirect_to institutes_url, notice: 'Institute was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institute
      @institute = Institute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institute_params
      params.require(:institute).permit(:name)
    end
end

app/helpers/institutes_helper.rb
module InstitutesHelper
end

app/views/institutes/_form.html.erb
<%= form_for(@institute) do |f| %>
  <% if @institute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@institute.errors.count, "error") %> prohibited this institute from being saved:</h2>

      <ul>
      <% @institute.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/institutes/edit.html.erb
<h1>Editing Institute</h1>

<%= render 'form' %>

<%= link_to 'Show', @institute %> |
<%= link_to 'Back', institutes_path %>

app/views/institutes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Institutes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @institutes.each do |institute| %>
      <tr>
        <td><%= institute.name %></td>
        <td><%= link_to 'Show', institute %></td>
        <td><%= link_to 'Edit', edit_institute_path(institute) %></td>
        <td><%= link_to 'Destroy', institute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Institute', new_institute_path %>

app/views/institutes/new.html.erb
<h1>New Institute</h1>

<%= render 'form' %>

<%= link_to 'Back', institutes_path %>

app/views/institutes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @institute.name %>
</p>

<%= link_to 'Edit', edit_institute_path(@institute) %> |
<%= link_to 'Back', institutes_path %>