config/routes.rb
Rails.application.routes.draw do

  resources :courses

  resources :departments

  resources :institutes

  devise_for :users

  resources :users, only: [:index, :show]

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'news' => 'static_pages#news'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  belongs_to :course
  belongs_to :admission

  def full_name
    if self.name.blank?
      self.email
    else
      self.name
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
    # @users = User.all we will replace this old code - you can delete this line

  	@users = User.page(params[:page]).per(30)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% provide(:title, "Usuários") %>
<div class="container">
  <div class="users row">
  	<%= paginate(@users) %>
    <% @users.each do |user| %>
      <div class="panel panel-default">
          <%= link_to user_path(user) do %>
          <div class="panel-body">
              <%= image_tag(user.avatar.url(:medium)) %>
              <p><%= user.full_name %></p>
          </div>
          <% end %>
      </div>
    <% end %>
    <%= paginate(@users) %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Perfil") %>
<h1><%= @user.email %></h1>
<ul>
    <li>Name: <%= @user.name %></li>
</ul>

<div class="row profile">
    <div class="col-sm-4 col-md-3">
        <%= image_tag(@user.avatar.url(:medium), class: 'avatar') %>
        <h1><%= @user.full_name %></h1>
        <ul>
            <%= content_tag(:li, ("Nome: " + @user.name)) unless @user.name.blank? %>
        </ul>
        <ul>
          <li><%= link_to "Usuários", users_path, class: "btn btn-default" %></li>
          <li><%= link_to "Institutos", institutes_path, class: "btn btn-default" %></li>
          <li><%= link_to "Departamentos", departments_path, class: "btn btn-default" %></li>
          <li><%= link_to "Cursos", courses_path, class: "btn btn-default" %></li>
        </ul>
    </div>
    <div class="feed">
        <h3>Social Feed Coming</h3>
        <p>Put a couple of lines of text here and see how it scrolls</p>
    </div>
</div>