config/routes.rb
Rails.application.routes.draw do

  resources :courses

  resources :departments

  resources :institutes

  devise_for :users

  resources :users, only: [:index, :show]

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'news' => 'static_pages#news'

end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
    </div>
<% end %>


<script>
    $('.alert').fadeOut(4000);
</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav class="navbar navbar-default navbar-static-bottom">
    
      <small> The Software Engennie I - Max, Victor, Arley.
      </small>
      <nav>
        <ul>
          <li><%= link_to "Sobre",   about_path %></li>
          <li><%= link_to "Contato", contact_path %></li>
          <li><%= link_to "News", news_path %></li>
        </ul>
      </nav>
    
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header id="custom-bootstrap-menu" class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">SOA</a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse navbar-menubuilder">
      <ul class="nav navbar-nav navbar-left">
          <li class="active"><%= link_to "Home", root_path %>
          </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Buscar">
          <button><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
        </div>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <p class="navbar-text pull-right">
          <% if user_signed_in? %>
             <li class="round-image-50"><%= image_tag(current_user.avatar.url(:thumb)) %></li>
            <li><strong><%= current_user.email %></strong>.</li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><span class="glyphicon glyphicon-user" aria-hidden="true">Conta</span><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %>
                </li>
                <li><%= link_to "Sair", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
                </li>
                <li class="divider"></li>
                <li><%= link_to "Ajuda", help_path, :class => 'navbar-link' %>
                </li>
              </ul>
            </li>
          <% else %>
            <%= link_to "Ajuda",   help_path, :class => 'navbar-link' %> | 
            <%= link_to "Cadastre se", new_user_registration_path, :class => 'navbar-link'  %>
          <% end %>
        </p>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | SOA - Sistema de Orientação Acadêmica</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
  	<% if notice %>
 		 	<p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
  		<p class="alert alert-danger"><%= alert %></p>
		<% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
</body>
</html>